### ISSUE TITLE
Create Skeleton Project

### ISSUE THREAD

**Issue by samuelsmithhk** [qdm12/Devops_RESTful#1]
**As a** developer
**I need** a skeleton project for the API
**So that** we can begin implementing features for the API

**Assumptions**:
- The API will be written in Python
- It will utilize the Flask library
- It will adhere to the principles of a proper RESTful API

**Acceptance Criteria**
- A git clone of this repo should pull down a skeleton flask project
- The project should be runnable without issue or any launch parameters using a recent Python runtime
- When running locally, should be able to access Flask server through localhost.

**Comment by qdm12** [comment]
he is killing it (last funny comment i promise)
