### ISSUE TITLE
Determine 3rd party services and configure Docker

### ISSUE THREAD

**Issue by qdm12** [qdm12/Devops_RESTful#10]
**As a** developer
**I need** to configure Docker to support the third party services needed such as for a database
**So that** I can deploy with Vagrant and the required third party services

**Assumptions**:
- The Vagrantfile is already configured
- The third party service can be used in Docker

**Acceptance Criteria**
- When running `vagrant up` the necessary third party service are automatically installed and configured.
- The service required to contain the database of assets common to all users should be determined.

**Comment by bhaveshvasandani** [comment]
1) Vagrant file reconfigured to create Redis data share directory and add the Redis docker container in the same.
2) updated the requirements.txt file for Redis to get installed upon vagrant up
3) Binding of environment varibles to be able to use redis_server to use the data.
