### ISSUE TITLE
[DUPLICATE OF #11] Obtain the value of an asset in a user's portfolio

### ISSUE THREAD

**Issue by qdm12** [qdm12/Devops_RESTful#12]
**As a** user
**I need** to obtain the total value of a certain asset of my portfolio
**So that** I can know the total value of an asset I have

**Assumptions**:
- Implemented in the RESTful API
- There is only one portfolio per user

**Acceptance Criteria**
- The value of an asset "palladium" of a portfolio will be obtained with a GET command to a URL `/api/v1/portfolios/john/palladium/value` It should return 0 if the user has not this asset.

**Comment by np1535** [comment]
Closing this issue - This functionality is handled with the nav request and also through a request based on a single asset value.
