### ISSUE TITLE
Setup Bluemix Pipeline

### ISSUE THREAD

**Issue by samuelsmithhk** [qdm12/Devops_RESTful#4]
**As a** developer
**I need** a space set up in Bluemix
**So that** I can deploy the project to Bluemix after implementing a change

**Assumptions**
- Does not need to be automated deployment at this stage

**Acceptance criteria**
- This story should result in a command that, when entered, will deploy my local changes into a Bluemix environment - with everything up and running.

**Comment by bhaveshvasandani** [comment]
PortfolioMgmt.mybluemix.net bluemix service created with python flask and Redis cloud

**Comment by bhaveshvasandani** [comment]
I think this is requirement for part 3 and should be taken in second sprint
