### ISSUE TITLE
Create a scalable container group

### ISSUE THREAD

**Issue by qdm12** [qdm12/Devops_RESTful#56]
**As a** developer
**I need** to have a container group running on Bluemix
**So that** the code is cloud scalable

**Assumptions**
- This uses the docker container created previously

**Acceptance criteria**
- You can run at least 2 instances of the container on cloud foundry
- The container group is bound to Redis
- Accessing the URL of this service has to work

**Comment by bhaveshvasandani** [comment]
https://portfoliocontainer.mybluemix.net/ container created with 2 instances.
