### ISSUE TITLE
Automate the test cases with Travis CI

### ISSUE THREAD

**Issue by qdm12** [qdm12/Devops_RESTful#59]
**As a** developer
**I need** to have automated test cases
**So that** each time a push or a pull request is made for the master branch, nothing is broken.

**Assumptions**
- A free Travis CI account has to be created
- Create and configure the `.travis.yml` file to run test cases for each push or pull requests to the master branch.

**Acceptance criteria**
- The push or pull request should be refused if at least one BDD or TDD test fails
- The push or pull request should be allowed if at all BDD and TDD test pass.

**Comment by RobinRule** [comment]
Working on, will be done before Monday night.

**Comment by qdm12** [comment]
Deadline is tomorrow night, how is it going ?
