### ISSUE TITLE
Installing Docker engine (cf ic) with Vagrantfile

### ISSUE THREAD

**Issue by qdm12** [qdm12/Devops_RESTful#81]
**As a** developer
**I want to** have the Docker engine installed in Vagrant with the Vagrantfile
**So that** I can use cf ic login to upload the container to Bluemix

Acceptance criteria:
- After doing a `vagrant up && vagrant ssh`, entering `cf ic login` should be recognized.

**Comment by bhaveshvasandani** [comment]
echo Y | cf install-plugin https://static-ice.ng.bluemix.net/ibm-containers-linux_x64
use this from within vagrant. Its there on the readme.

**Comment by bhaveshvasandani** [comment]
Please close this if it works. :)
